const saCities = [
    {
        city: "Johannesburg", 
        latitude: "-26.2044", 
        longitude: "28.0416", 
        country: "South Africa", 
        iso2: "ZA", 
        admin_name: "Gauteng", 
        capital: "admin", 
        population: "4434827", 
        population_proper: "4434827"
    }, 
    {
        city: "Vereeniging", 
        latitude: "-26.6736", 
        longitude: "27.9319", 
        country: "South Africa", 
        iso2: "ZA", 
        province: "Gauteng", 
        capital: "", 
        population: "1074000", 
        population_proper: "474681"
    }, 
    {
        city: "Pietermaritzburg", 
        latitude: "-29.5833", 
        longitude: "30.4167", 
        country: "South Africa", 
        iso2: "ZA", 
        province: "KwaZulu-Natal", 
        capital: "admin", 
        population: "750845", 
        population_proper: "490951"
    }, 
    {
        city: "Pretoria", 
        latitude: "-25.7464", 
        longitude: "28.1881", 
        country: "South Africa", 
        iso2: "ZA", 
        province: "Gauteng", 
        capital: "primary", 
        population: "741651", 
        population_proper: "741651"
    }, 
    {
        city: "Durban", 
        latitude: "-29.8583", 
        longitude: "31.0250", 
        country: "South Africa", 
        iso2: "ZA", 
        province: "KwaZulu-Natal", 
        capital: "", 
        population: "595061", 
        population_proper: "595061"
    }, 
    {
        city: "Cape Town", 
        latitude: "-33.9250", 
        longitude: "18.4250", 
        country: "South Africa", 
        iso2: "ZA", 
        province: "Western Cape", 
        capital: "primary", 
        population: "433688", 
        population_proper: "433688"
    }, 
    {
        city: "Welkom", 
        latitude: "-27.9831", 
        longitude: "26.7208", 
        country: "South Africa", 
        iso2: "ZA", 
        province: "Free State", 
        capital: "", 
        population: "431944", 
        population_proper: "126079"
    }, 
    {
        city: "East London", 
        latitude: "-33.0153", 
        longitude: "27.9116", 
        country: "South Africa", 
        iso2: "ZA", 
        province: "Eastern Cape", 
        capital: "", 
        population: "338627", 
        population_proper: "338627"
    }, 
    {
        city: "Randburg", 
        latitude: "-26.0936", 
        longitude: "28.0064", 
        country: "South Africa", 
        iso2: "ZA", 
        province: "Gauteng", 
        capital: "", 
        population: "337053", 
        population_proper: "337053"
    }, 
    {
        city: "Roodepoort", 
        latitude: "-26.1625", 
        longitude: "27.8725", 
        country: "South Africa", 
        iso2: "ZA", 
        province: "Gauteng", 
        capital: "", 
        population: "326416", 
        population_proper: "326416"
    }, 
    {
        city: "Port Elizabeth", 
        latitude: "-33.9581", 
        longitude: "25.6000", 
        country: "South Africa", 
        iso2: "ZA", 
        province: "Eastern Cape", 
        capital: "", 
        population: "312392", 
        population_proper: "312392"
    }, 
    {
        city: "Bloemfontein", 
        latitude: "-29.1000", 
        longitude: "26.2167", 
        country: "South Africa", 
        iso2: "ZA", 
        province: "Free State", 
        capital: "primary", 
        population: "256185", 
        population_proper: "256185"
    }, 
    {
        city: "Centurion", 
        latitude: "-25.8603", 
        longitude: "28.1894", 
        country: "South Africa", 
        iso2: "ZA", 
        province: "Gauteng", 
        capital: "", 
        population: "236580", 
        population_proper: "236580"
    }, 
    {
        city: "Springs", 
        latitude: "-26.2547", 
        longitude: "28.4428", 
        country: "South Africa", 
        iso2: "ZA", 
        province: "Gauteng", 
        capital: "", 
        population: "236083", 
        population_proper: "186394"
    }, 
    {
        city: "Sandton", 
        latitude: "-26.1070", 
        longitude: "28.0517", 
        country: "South Africa", 
        iso2: "ZA", 
        province: "Gauteng", 
        capital: "", 
        population: "222415", 
        population_proper: "222415"
    }, 
    {
        city: "Polokwane", 
        latitude: "-23.9000", 
        longitude: "29.4500", 
        country: "South Africa", 
        iso2: "ZA", 
        province: "Limpopo", 
        capital: "admin", 
        population: "220045", 
        population_proper: "123749"
    }, 
    {
        city: "Klerksdorp", 
        latitude: "-26.8667", 
        longitude: "26.6667", 
        country: "South Africa", 
        iso2: "ZA", 
        province: "North West", 
        capital: "", 
        population: "178921", 
        population_proper: "147804"
    }, 
    {
        city: "Rustenburg", 
        latitude: "-25.6500", 
        longitude: "27.2400", 
        country: "South Africa", 
        iso2: "ZA", 
        province: "North West", 
        capital: "", 
        population: "165976", 
        population_proper: "124064"
    }, 
    {
        city: "Kimberley", 
        latitude: "-28.7386", 
        longitude: "24.7586", 
        country: "South Africa", 
        iso2: "ZA", 
        province: "Northern Cape", 
        capital: "admin", 
        population: "165264", 
        population_proper: "142089"
    }, 
    {
        city: "Bhisho", 
        latitude: "-32.8494", 
        longitude: "27.4381", 
        country: "South Africa", 
        iso2: "ZA", 
        province: "Eastern Cape", 
        capital: "admin", 
        population: "160997", 
        population_proper: "137287"
    }, 
    {
        city: "Benoni", 
        latitude: "-26.1883", 
        longitude: "28.3206", 
        country: "South Africa", 
        iso2: "ZA", 
        province: "Gauteng", 
        capital: "", 
        population: "158777", 
        population_proper: "158777"
    }, 
    {
        city: "George", 
        latitude: "-33.9667", 
        longitude: "22.4500", 
        country: "South Africa", 
        iso2: "ZA", 
        province: "Western Cape", 
        capital: "", 
        population: "157394", 
        population_proper: "157394"
    }, 
    {
        city: "Middelburg", 
        latitude: "-25.7684", 
        longitude: "29.4783", 
        country: "South Africa", 
        iso2: "ZA", 
        province: "Mpumalanga", 
        capital: "", 
        population: "154706", 
        population_proper: "93790"
    }, 
    {
        city: "Vryheid", 
        latitude: "-27.7694", 
        longitude: "30.7914", 
        country: "South Africa", 
        iso2: "ZA", 
        province: "KwaZulu-Natal", 
        capital: "", 
        population: "150012", 
        population_proper: "66717"
    }, 
    {
        city: "Potchefstroom", 
        latitude: "-26.7150", 
        longitude: "27.1033", 
        country: "South Africa", 
        iso2: "ZA", 
        province: "North West", 
        capital: "", 
        population: "148804", 
        population_proper: "148804"
    }, 
    {
        city: "Umtata", 
        latitude: "-31.5800", 
        longitude: "28.7900", 
        country: "South Africa", 
        iso2: "ZA", 
        province: "Eastern Cape", 
        capital: "", 
        population: "137772", 
        population_proper: "78663"
    }, 
    {
        city: "Brits", 
        latitude: "-25.6167", 
        longitude: "27.7667", 
        country: "South Africa", 
        iso2: "ZA", 
        province: "North West", 
        capital: "", 
        population: "122497", 
        population_proper: "39947"
    }, 
    {
        city: "Alberton", 
        latitude: "-26.2672", 
        longitude: "28.1219", 
        country: "South Africa", 
        iso2: "ZA", 
        province: "Gauteng", 
        capital: "", 
        population: "121536", 
        population_proper: "121536"
    }, 
    {
        city: "Upington", 
        latitude: "-28.4572", 
        longitude: "21.2425", 
        country: "South Africa", 
        iso2: "ZA", 
        province: "Northern Cape", 
        capital: "", 
        population: "121189", 
        population_proper: "121189"
    }, 
    {
        city: "Paarl", 
        latitude: "-33.7242", 
        longitude: "18.9558", 
        country: "South Africa", 
        iso2: "ZA", 
        province: "Western Cape", 
        capital: "", 
        population: "112045", 
        population_proper: "112045"
    }, 
    {
        city: "Queenstown", 
        latitude: "-31.9000", 
        longitude: "26.8833", 
        country: "South Africa", 
        iso2: "ZA", 
        province: "Eastern Cape", 
        capital: "", 
        population: "105309", 
        population_proper: "87240"
    }, 
    {
        city: "Mmabatho", 
        latitude: "-25.8500", 
        longitude: "25.6333", 
        country: "South Africa", 
        iso2: "ZA", 
        province: "North West", 
        capital: "", 
        population: "104428", 
        population_proper: "76754"
    }, 
    {
        city: "Kroonstad", 
        latitude: "-27.6456", 
        longitude: "27.2317", 
        country: "South Africa", 
        iso2: "ZA", 
        province: "Free State", 
        capital: "", 
        population: "103992", 
        population_proper: "72835"
    }, 
    {
        city: "Uitenhage", 
        latitude: "-33.7500", 
        longitude: "25.4000", 
        country: "South Africa", 
        iso2: "ZA", 
        province: "Eastern Cape", 
        capital: "", 
        population: "103639", 
        population_proper: "103639"
    }, 
    {
        city: "Bethal", 
        latitude: "-26.4500", 
        longitude: "29.4500", 
        country: "South Africa", 
        iso2: "ZA", 
        province: "Mpumalanga", 
        capital: "", 
        population: "101919", 
        population_proper: "90450"
    }, 
    {
        city: "Worcester", 
        latitude: "-33.6450", 
        longitude: "19.4436", 
        country: "South Africa", 
        iso2: "ZA", 
        province: "Western Cape", 
        capital: "", 
        population: "97098", 
        population_proper: "97098"
    }, 
    {
        city: "Vanderbijlpark", 
        latitude: "-26.6992", 
        longitude: "27.8356", 
        country: "South Africa", 
        iso2: "ZA", 
        province: "Gauteng", 
        capital: "", 
        population: "95840", 
        population_proper: "95840"
    }, 
    {
        city: "Grahamstown", 
        latitude: "-33.2996", 
        longitude: "26.5200", 
        country: "South Africa", 
        iso2: "ZA", 
        province: "Eastern Cape", 
        capital: "", 
        population: "91548", 
        population_proper: "49083"
    }, 
    {
        city: "Standerton", 
        latitude: "-26.9500", 
        longitude: "29.2500", 
        country: "South Africa", 
        iso2: "ZA", 
        province: "Mpumalanga", 
        capital: "", 
        population: "74021", 
        population_proper: "18093"
    }, 
    {
        city: "Brakpan", 
        latitude: "-26.2353", 
        longitude: "28.3700", 
        country: "South Africa", 
        iso2: "ZA", 
        province: "Gauteng", 
        capital: "", 
        population: "73080", 
        population_proper: "73080"
    }, 
    {
        city: "Thohoyandou", 
        latitude: "-22.9500", 
        longitude: "30.4833", 
        country: "South Africa", 
        iso2: "ZA", 
        province: "Limpopo", 
        capital: "", 
        population: "69453", 
        population_proper: "69453"
    }, 
    {
        city: "Saldanha", 
        latitude: "-32.9978", 
        longitude: "17.9456", 
        country: "South Africa", 
        iso2: "ZA", 
        province: "Western Cape", 
        capital: "", 
        population: "68284", 
        population_proper: "6654"
    }, 
    {
        city: "Tzaneen", 
        latitude: "-23.8333", 
        longitude: "30.1667", 
        country: "South Africa", 
        iso2: "ZA", 
        province: "Limpopo", 
        capital: "", 
        population: "67245", 
        population_proper: "16954"
    }, 
    {
        city: "Graaff-Reinet", 
        latitude: "-32.2522", 
        longitude: "24.5406", 
        country: "South Africa", 
        iso2: "ZA", 
        province: "Eastern Cape", 
        capital: "", 
        population: "62896", 
        population_proper: "3021"
    }, 
    {
        city: "Oudtshoorn", 
        latitude: "-33.5833", 
        longitude: "22.2000", 
        country: "South Africa", 
        iso2: "ZA", 
        province: "Western Cape", 
        capital: "", 
        population: "61507", 
        population_proper: "61507"
    }, 
    {
        city: "Mossel Bay", 
        latitude: "-34.1833", 
        longitude: "22.1333", 
        country: "South Africa", 
        iso2: "ZA", 
        province: "Western Cape", 
        capital: "", 
        population: "59031", 
        population_proper: "59031"
    }, 
    {
        city: "Port Shepstone", 
        latitude: "-30.7411", 
        longitude: "30.4547", 
        country: "South Africa", 
        iso2: "ZA", 
        province: "KwaZulu-Natal", 
        capital: "", 
        population: "52793", 
        population_proper: "21858"
    }, 
    {
        city: "Knysna", 
        latitude: "-34.0356", 
        longitude: "23.0489", 
        country: "South Africa", 
        iso2: "ZA", 
        province: "Western Cape", 
        capital: "", 
        population: "51078", 
        population_proper: "51078"
    }, 
    {
        city: "Vryburg", 
        latitude: "-26.9500", 
        longitude: "24.7333", 
        country: "South Africa", 
        iso2: "ZA", 
        province: "North West", 
        capital: "", 
        population: "49588", 
        population_proper: "13590"
    }, 
    {
        city: "Ladysmith", 
        latitude: "-28.5539", 
        longitude: "29.7825", 
        country: "South Africa", 
        iso2: "ZA", 
        province: "KwaZulu-Natal", 
        capital: "", 
        population: "47375", 
        population_proper: "47375"
    }, 
    {
        city: "Beaufort West", 
        latitude: "-32.3500", 
        longitude: "22.5833", 
        country: "South Africa", 
        iso2: "ZA", 
        province: "Western Cape", 
        capital: "", 
        population: "44737", 
        population_proper: "11404"
    }, 
    {
        city: "Aliwal North", 
        latitude: "-30.7000", 
        longitude: "26.7000", 
        country: "South Africa", 
        iso2: "ZA", 
        province: "Eastern Cape", 
        capital: "", 
        population: "44436", 
        population_proper: "8410"
    }, 
    {
        city: "Volksrust", 
        latitude: "-27.3667", 
        longitude: "29.8833", 
        country: "South Africa", 
        iso2: "ZA", 
        province: "Mpumalanga", 
        capital: "", 
        population: "43378", 
        population_proper: "7411"
    }, 
    {
        city: "Musina", 
        latitude: "-22.3381", 
        longitude: "30.0417", 
        country: "South Africa", 
        iso2: "ZA", 
        province: "Limpopo", 
        capital: "", 
        population: "42678", 
        population_proper: "42678"
    }, 
    {
        city: "Vredenburg", 
        latitude: "-32.9000", 
        longitude: "17.9833", 
        country: "South Africa", 
        iso2: "ZA", 
        province: "Western Cape", 
        capital: "", 
        population: "38382", 
        population_proper: "38382"
    }, 
    {
        city: "Malmesbury", 
        latitude: "-33.4500", 
        longitude: "18.7333", 
        country: "South Africa", 
        iso2: "ZA", 
        province: "Western Cape", 
        capital: "", 
        population: "35897", 
        population_proper: "35897"
    }, 
    {
        city: "Lebowakgomo", 
        latitude: "-24.3050", 
        longitude: "29.5650", 
        country: "South Africa", 
        iso2: "ZA", 
        province: "Limpopo", 
        capital: "", 
        population: "33308", 
        population_proper: "397"
    }, 
    {
        city: "Cradock", 
        latitude: "-32.1833", 
        longitude: "25.6167", 
        country: "South Africa", 
        iso2: "ZA", 
        province: "Eastern Cape", 
        capital: "", 
        population: "32898", 
        population_proper: "32898"
    }, 
    {
        city: "De Aar", 
        latitude: "-30.6500", 
        longitude: "24.0167", 
        country: "South Africa", 
        iso2: "ZA", 
        province: "Northern Cape", 
        capital: "", 
        population: "32318", 
        population_proper: "5021"
    }, 
    {
        city: "Ulundi", 
        latitude: "-28.3350", 
        longitude: "31.4161", 
        country: "South Africa", 
        iso2: "ZA", 
        province: "KwaZulu-Natal", 
        capital: "", 
        population: "29132", 
        population_proper: "29132"
    }, 
    {
        city: "Jeffrey\u2019s Bay", 
        latitude: "-34.0333", 
        longitude: "24.9167", 
        country: "South Africa", 
        iso2: "ZA", 
        province: "Eastern Cape", 
        capital: "", 
        population: "27107", 
        population_proper: "27107"
    }, 
    {
        city: "Lichtenburg", 
        latitude: "-26.1500", 
        longitude: "26.1667", 
        country: "South Africa", 
        iso2: "ZA", 
        province: "North West", 
        capital: "", 
        population: "26338", 
        population_proper: "26338"
    }, 
    {
        city: "Hermanus", 
        latitude: "-34.4167", 
        longitude: "19.3000", 
        country: "South Africa", 
        iso2: "ZA", 
        province: "Western Cape", 
        capital: "", 
        population: "25153", 
        population_proper: "7396"
    }, 
    {
        city: "Carletonville", 
        latitude: "-26.3581", 
        longitude: "27.3981", 
        country: "South Africa", 
        iso2: "ZA", 
        province: "Gauteng", 
        capital: "", 
        population: "23000", 
        population_proper: "23000"
    }, 
    {
        city: "Komatipoort", 
        latitude: "-25.4333", 
        longitude: "31.9500", 
        country: "South Africa", 
        iso2: "ZA", 
        province: "Mpumalanga", 
        capital: "", 
        population: "20508", 
        population_proper: "159"
    }, 
    {
        city: "Middelburg", 
        latitude: "-31.4939", 
        longitude: "25.0172", 
        country: "South Africa", 
        iso2: "ZA", 
        province: "Eastern Cape", 
        capital: "", 
        population: "18164", 
        population_proper: "3764"
    }, 
    {
        city: "Port Alfred", 
        latitude: "-33.6000", 
        longitude: "26.8833", 
        country: "South Africa", 
        iso2: "ZA", 
        province: "Eastern Cape", 
        capital: "", 
        population: "17959", 
        population_proper: "795"
    }, 
    {
        city: "Swellendam", 
        latitude: "-34.0231", 
        longitude: "20.4400", 
        country: "South Africa", 
        iso2: "ZA", 
        province: "Western Cape", 
        capital: "", 
        population: "17537", 
        population_proper: "17537"
    }, 
    {
        city: "Bloemhof", 
        latitude: "-27.6500", 
        longitude: "25.5900", 
        country: "South Africa", 
        iso2: "ZA", 
        province: "North West", 
        capital: "", 
        population: "17122", 
        population_proper: "4203"
    }, 
    {
        city: "Bethlehem", 
        latitude: "-28.2333", 
        longitude: "28.3000", 
        country: "South Africa", 
        iso2: "ZA", 
        province: "Free State", 
        capital: "", 
        population: "16236", 
        population_proper: "16236"
    }, 
    {
        city: "Montagu", 
        latitude: "-33.7833", 
        longitude: "20.1167", 
        country: "South Africa", 
        iso2: "ZA", 
        province: "Western Cape", 
        capital: "", 
        population: "15176", 
        population_proper: "15176"
    }, 
    {
        city: "Mahikeng", 
        latitude: "-25.8653", 
        longitude: "25.6442", 
        country: "South Africa", 
        iso2: "ZA", 
        province: "North West", 
        capital: "admin", 
        population: "15117", 
        population_proper: "15117"
    }, 
    {
        city: "Bredasdorp", 
        latitude: "-34.5333", 
        longitude: "20.0417", 
        country: "South Africa", 
        iso2: "ZA", 
        province: "Western Cape", 
        capital: "", 
        population: "14936", 
        population_proper: "1970"
    }, 
    {
        city: "Phalaborwa", 
        latitude: "-23.9333", 
        longitude: "31.1167", 
        country: "South Africa", 
        iso2: "ZA", 
        province: "Limpopo", 
        capital: "", 
        population: "13108", 
        population_proper: "13108"
    }, 
    {
        city: "Caledon", 
        latitude: "-34.2300", 
        longitude: "19.4283", 
        country: "South Africa", 
        iso2: "ZA", 
        province: "Western Cape", 
        capital: "", 
        population: "13020", 
        population_proper: "13020"
    }, 
    {
        city: "Moorreesburg", 
        latitude: "-33.1500", 
        longitude: "18.6667", 
        country: "South Africa", 
        iso2: "ZA", 
        province: "Western Cape", 
        capital: "", 
        population: "12877", 
        population_proper: "12877"
    }, 
    {
        city: "Colesberg", 
        latitude: "-30.7167", 
        longitude: "25.1000", 
        country: "South Africa", 
        iso2: "ZA", 
        province: "Northern Cape", 
        capital: "", 
        population: "12423", 
        population_proper: "2559"
    }, 
    {
        city: "Brandfort", 
        latitude: "-28.7000", 
        longitude: "26.4667", 
        country: "South Africa", 
        iso2: "ZA", 
        province: "Free State", 
        capital: "", 
        population: "12091", 
        population_proper: "289"
    }, 
    {
        city: "Piketberg", 
        latitude: "-32.9000", 
        longitude: "18.7667", 
        country: "South Africa", 
        iso2: "ZA", 
        province: "Western Cape", 
        capital: "", 
        population: "12075", 
        population_proper: "12075"
    }, 
    {
        city: "Saint Helena Bay", 
        latitude: "-32.7583", 
        longitude: "18.0278", 
        country: "South Africa", 
        iso2: "ZA", 
        province: "Western Cape", 
        capital: "", 
        population: "11529", 
        population_proper: "11529"
    }, 
    {
        city: "Prieska", 
        latitude: "-29.6683", 
        longitude: "22.7439", 
        country: "South Africa", 
        iso2: "ZA", 
        province: "Northern Cape", 
        capital: "", 
        population: "11236", 
        population_proper: "4045"
    }, 
    {
        city: "Velddrif", 
        latitude: "-32.7667", 
        longitude: "18.1667", 
        country: "South Africa", 
        iso2: "ZA", 
        province: "Western Cape", 
        capital: "", 
        population: "11017", 
        population_proper: "11017"
    }, 
    {
        city: "Springbok", 
        latitude: "-29.6667", 
        longitude: "17.8833", 
        country: "South Africa", 
        iso2: "ZA", 
        province: "Northern Cape", 
        capital: "", 
        population: "10438", 
        population_proper: "2809"
    }, 
    {
        city: "Darling", 
        latitude: "-33.3833", 
        longitude: "18.3833", 
        country: "South Africa", 
        iso2: "ZA", 
        province: "Western Cape", 
        capital: "", 
        population: "10420", 
        population_proper: "10420"
    }, 
    {
        city: "Kuruman", 
        latitude: "-27.4597", 
        longitude: "23.4125", 
        country: "South Africa", 
        iso2: "ZA", 
        province: "Northern Cape", 
        capital: "", 
        population: "10006", 
        population_proper: "9093"
    }, 
    {
        city: "Villiersdorp", 
        latitude: "-33.9833", 
        longitude: "19.2833", 
        country: "South Africa", 
        iso2: "ZA", 
        province: "Western Cape", 
        capital: "", 
        population: "10004", 
        population_proper: "10004"
    }, 
    {
        city: "Tulbagh", 
        latitude: "-33.2850", 
        longitude: "19.1378", 
        country: "South Africa", 
        iso2: "ZA", 
        province: "Western Cape", 
        capital: "", 
        population: "8969", 
        population_proper: "8969"
    }, 
    {
        city: "Saron", 
        latitude: "-33.1810", 
        longitude: "19.0100", 
        country: "South Africa", 
        iso2: "ZA", 
        province: "Western Cape", 
        capital: "", 
        population: "7843", 
        population_proper: "7843"
    }, 
    {
        city: "Clanwilliam", 
        latitude: "-32.1786", 
        longitude: "18.8911", 
        country: "South Africa", 
        iso2: "ZA", 
        province: "Western Cape", 
        capital: "", 
        population: "7674", 
        population_proper: "7674"
    }, 
    {
        city: "Citrusdal", 
        latitude: "-32.5894", 
        longitude: "19.0147", 
        country: "South Africa", 
        iso2: "ZA", 
        province: "Western Cape", 
        capital: "", 
        population: "7177", 
        population_proper: "7177"
    }, 
    {
        city: "Porterville", 
        latitude: "-33.0000", 
        longitude: "18.9833", 
        country: "South Africa", 
        iso2: "ZA", 
        province: "Western Cape", 
        capital: "", 
        population: "7057", 
        population_proper: "7057"
    }, 
    {
        city: "Kleinmond", 
        latitude: "-34.3500", 
        longitude: "19.0333", 
        country: "South Africa", 
        iso2: "ZA", 
        province: "Western Cape", 
        capital: "", 
        population: "6634", 
        population_proper: "6634"
    }, 
    {
        city: "Hopefield", 
        latitude: "-33.0667", 
        longitude: "18.3500", 
        country: "South Africa", 
        iso2: "ZA", 
        province: "Western Cape", 
        capital: "", 
        population: "6460", 
        population_proper: "6460"
    }, 
    {
        city: "Vanrhynsdorp", 
        latitude: "-31.6167", 
        longitude: "18.7167", 
        country: "South Africa", 
        iso2: "ZA", 
        province: "Western Cape", 
        capital: "", 
        population: "6272", 
        population_proper: "6272"
    }, 
    {
        city: "Klawer", 
        latitude: "-31.7833", 
        longitude: "18.6167", 
        country: "South Africa", 
        iso2: "ZA", 
        province: "Western Cape", 
        capital: "", 
        population: "6234", 
        population_proper: "6234"
    }, 
    {
        city: "Lambert\u2019s Bay", 
        latitude: "-32.0833", 
        longitude: "18.3000", 
        country: "South Africa", 
        iso2: "ZA", 
        province: "Western Cape", 
        capital: "", 
        population: "6120", 
        population_proper: "6120"
    }, 
    {
        city: "Port Saint John\u2019s", 
        latitude: "-31.6288", 
        longitude: "29.5369", 
        country: "South Africa", 
        iso2: "ZA", 
        province: "Eastern Cape", 
        capital: "", 
        population: "5939", 
        population_proper: "5939"
    }, 
    {
        city: "Carnarvon", 
        latitude: "-30.9667", 
        longitude: "22.1333", 
        country: "South Africa", 
        iso2: "ZA", 
        province: "Northern Cape", 
        capital: "", 
        population: "5785", 
        population_proper: "5785"
    }, 
    {
        city: "Genadendal", 
        latitude: "-34.0333", 
        longitude: "19.5500", 
        country: "South Africa", 
        iso2: "ZA", 
        province: "Western Cape", 
        capital: "", 
        population: "5663", 
        population_proper: "5663"
    }, 
    {
        city: "Riviersonderend", 
        latitude: "-34.1500", 
        longitude: "19.9000", 
        country: "South Africa", 
        iso2: "ZA", 
        province: "Western Cape", 
        capital: "", 
        population: "5245", 
        population_proper: "5245"
    }, 
    {
        city: "Onrus", 
        latitude: "-34.4122", 
        longitude: "19.1700", 
        country: "South Africa", 
        iso2: "ZA", 
        province: "Western Cape", 
        capital: "", 
        population: "5151", 
        population_proper: "5151"
    }, 
    {
        city: "Pofadder", 
        latitude: "-29.1286", 
        longitude: "19.3947", 
        country: "South Africa", 
        iso2: "ZA", 
        province: "Northern Cape", 
        capital: "", 
        population: "4220", 
        population_proper: "4220"
    }, 
    {
        city: "Barrydale", 
        latitude: "-33.9000", 
        longitude: "20.7333", 
        country: "South Africa", 
        iso2: "ZA", 
        province: "Western Cape", 
        capital: "", 
        population: "4156", 
        population_proper: "4156"
    }, 
    {
        city: "Steytlerville", 
        latitude: "-33.3328", 
        longitude: "24.3447", 
        country: "South Africa", 
        iso2: "ZA", 
        province: "Eastern Cape", 
        capital: "", 
        population: "3986", 
        population_proper: "3986"
    }, 
    {
        city: "Rawsonville", 
        latitude: "-33.6847", 
        longitude: "19.3150", 
        country: "South Africa", 
        iso2: "ZA", 
        province: "Western Cape", 
        capital: "", 
        population: "3099", 
        population_proper: "3099"
    }, 
    {
        city: "Fraserburg", 
        latitude: "-31.9144", 
        longitude: "21.5119", 
        country: "South Africa", 
        iso2: "ZA", 
        province: "Northern Cape", 
        capital: "", 
        population: "3029", 
        population_proper: "3029"
    }, 
    {
        city: "Suurbraak", 
        latitude: "-34.0049", 
        longitude: "20.6528", 
        country: "South Africa", 
        iso2: "ZA", 
        province: "Western Cape", 
        capital: "", 
        population: "2252", 
        population_proper: "2252"
    }, 
    {
        city: "Nelspruit", 
        latitude: "-25.4745", 
        longitude: "30.9703", 
        country: "South Africa", 
        iso2: "ZA", 
        province: "Mpumalanga", 
        capital: "admin", 
        population: "", 
        population_proper: ""
    }
]



console.log(parseFloat(saCities[1].latitude));
// console.log(saCities[0].lat);